server:
  port: 80
spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=moorgen
    username: sa
    password: 980813

mybatis:
  type-aliases-package: fishman.fish.wxdemo.bean   #实体类别名
  mapper-locations: classpath:mybatis/mapper/*.xml  #对应的sql配置文件
  config-location: classpath:mybatis/mybatis-config.xml  #mybatis主配置文件


#微信公众号一些参数配置
wx:
  appID: "wxc6d0cb3e75649eca"
  appSecret: "1e38d886b05e51c240ae23540ac849b6"
  token: "fishman"
  openID: "os8JR6qBb-WtNJYr0MG_aeTQpSQ4"
  tempID: "b6j0M9VwkjTCHncmUDrsp459opxvA_7gHYK6Ia5CqDI"
  currentURL: "http://fishman.free.idcfengye.com"

#微信聊天机器人
robot:
  userID: "fishman"
  appID: "1616210274861"
  apiKey: "MIIQGO3ISMIX965PVPKU3BECVQQSKM9JDHP5OOZA68DWTX690N"
  ip: "2930306573"

logging:
  level:
    fishman.fish.wxdemo: debug  #设置日志级别
